### ISSUE TITLE
CashLetterControl Record or Bundle Control Record  are mandatory but are not checked inside icl json

### ISSUE THREAD

**Issue by adotiyal** [moov-io/imagecashletter#228]
**What were you trying to do?**

 **Do:**

_curl -X POST -H "content-type: application/json" localhost:8083/files/create --data @./test/testdata/my-icl.json_

where my-icl.json is:
```json
{
	"fileHeader": {
		"testIndicator": "T",
		"immediateDestination": "221970443",
		"immediateOrigin": "021913655",
		"fileCreationDate": "2022-03-23T17:02:01Z",
		"fileCreationTime": "2022-03-23T17:02:01Z",
		"recordType": "01",
		"standardLevel": "03",
		"resendIndicator": "N"
	},
	"cashLetters": [{
		"cashLetterHeader": {
			"recordType": "10",
			"collectionTypeIndicator": "01",
			"destinationRoutingNumber": "221970443",
			"eceInstitutionRoutingNumber": "221970443",
			"cashLetterBusinessDate": "2022-03-23T17:02:01Z",
			"cashLetterCreationDate": "2022-03-23T17:02:01Z",
			"cashLetterCreationTime": "2022-03-23T17:02:01Z",
			"recordTypeIndicator": "I",
			"documentationTypeIndicator": "G",
			"cashLetterID": "2b0212d8-5738-4348-be5c-9412db343b74"
		},
		"bundles": [{
			"bundleControl": {
				"creditTotalIndicator": 0,
				"userField": "",
				"bundleImagesCount": 2,
				"micrValidTotalAmount": 200000,
				"bundleTotalAmount": 200000,
				"bundleitemsCount": 14,
				"id": ""
			},
			"bundleHeader": {
				"recordType": "20",
				"collectionTypeIndicator": "01",
				"destinationRoutingNumber": "231380104",
				"eceInstitutionRoutingNumber": "221970443",
				"bundleBusinessDate": "2022-03-23T17:02:01Z",
				"bundleCreationDate": "2022-03-23T17:02:01Z"
			},
			"checks": [{
				"recordType": "25",
				"payorBankRoutingNumber": "231380104",
				"payorBankCheckDigit": "2",
				"itemAmount": 100,
				"eceInstitutionItemSequenceNumber": "1",
				"addendumCount": 0,
				"documentationTypeIndicator": "G",
				"bofdIndicator": "U",
				"imageViewDetail": [{
					"imageCreatorRoutingNumber": "231380104",
					"imageCreatorDate": "2022-03-23T17:02:01Z",
					"viewSideIndicator": 0,
					"recordType": "50",
					"imageIndicator": 1,
					"imageViewFormatIndicator": "00",
					"imageViewCompressionFormatIndicator": "00",
					"viewDescriptor": "00",
					"digitalSignatureIndicator": 0
				}],
				"imageViewData": [{
					"eceInstitutionRoutingNumber": "221970443",
					"bundleBusinessDate": "2022-03-23T17:02:01Z",
					"eceInstitutionItemSequenceNumber": "1",
					"imageData": "IA==",
					"lengthImageData": "1",
					"recordType": "52",
					"clippingOrigin": 0,
					"lengthImageReferenceKey": "0",
					"lengthOfDigitalSignature": "0"
				}],
				"correctionIndicator": 1
			}]
		}]
	}]
}
```

**Note:** _CashLetterControl Record is missing from json._

**Response:**

`curl -X POST -H "content-type: application/json" localhost:8083/files/create --data @./test/testdata/my-icl.json -vv`

```
*   Trying ::1:8083...
* Connected to localhost (::1) port 8083 (#0)
> POST /files/create HTTP/1.1
> Host: localhost:8083
> User-Agent: curl/7.77.0
> Accept: */*
> content-type: application/json
> Content-Length: 2244
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Content-Type: application/json; charset=utf-8
< Date: Wed, 23 Mar 2022 17:41:22 GMT
< Transfer-Encoding: chunked
< 
{"id":"ac3293b1ec679b0c7002a38180512ac0aab757f5",.............}
```

**What did you expect to see?**

Since CashLetterControl Record is a mandatory field I expect that the file is not created and I get non 2xx code back.

**What did you see?**

Got :
_HTTP/1.1 201 Created_

And when I request the content for the ID:
` curl localhost:8083/files/ac3293b1ec679b0c7002a38180512ac0aab757f5/contents`

, I see a panic in go code:

```
icl_1               | 2022/03/23 17:45:03 http: panic serving 172.22.0.1:59414: runtime error: invalid memory address or nil pointer dereference
icl_1               | goroutine 54 [running]:
icl_1               | net/http.(*conn).serve.func1()
icl_1               | 	/usr/local/go/src/net/http/server.go:1802 +0xb9
icl_1               | panic({0x892d80, 0xcf7fd0})
icl_1               | 	/usr/local/go/src/runtime/panic.go:1047 +0x266
icl_1               | github.com/moov-io/imagecashletter.(*CashLetterControl).String(0x0)
icl_1               | 	/go/src/github.com/moov-io/imagecashletter/cashLetterControl.go:117 +0xff
icl_1               | github.com/moov-io/imagecashletter.(*Writer).writeLine(0xc0000ac060, {0x9c7d48, 0x0})
icl_1               | 	/go/src/github.com/moov-io/imagecashletter/writer.go:58 +0x30
icl_1               | github.com/moov-io/imagecashletter.(*Writer).writeCashLetter(0xc0000ac060, 0x9c7e88)
icl_1               | 	/go/src/github.com/moov-io/imagecashletter/writer.go:157 +0x191
icl_1               | github.com/moov-io/imagecashletter.(*Writer).Write(0xc0000ac060, 0xc0001d2000)
icl_1               | 	/go/src/github.com/moov-io/imagecashletter/writer.go:122 +0x88
icl_1               | main.getFileContents.func1({0x9c9718, 0xc0002580e0}, 0xc000334200)
icl_1               | 	/go/src/github.com/moov-io/imagecashletter/cmd/server/files.go:303 +0x396
icl_1               | net/http.HandlerFunc.ServeHTTP(0xc000334100, {0x9c9718, 0xc0002580e0}, 0xd0e500)
icl_1               | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
icl_1               | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002400c0, {0x9c9718, 0xc0002580e0}, 0xc000334000)
icl_1               | 	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
icl_1               | net/http.serverHandler.ServeHTTP({0xc0002900c0}, {0x9c9718, 0xc0002580e0}, 0xc000334000)
icl_1               | 	/usr/local/go/src/net/http/server.go:2879 +0x43b
icl_1               | net/http.(*conn).serve(0xc0001c0140, {0x9cb6d8, 0xc00026a660})
icl_1               | 	/usr/local/go/src/net/http/server.go:1930 +0xb08
icl_1               | created by net/http.(*Server).Serve
icl_1               | 	/usr/local/go/src/net/http/server.go:3034 +0x4e8
```

Panic is due to the fact that CashLetterControl Record is missing.

**How can we reproduce the problem?**

It can be reproduced by running the steps above.

**Resolution**
Check for mandatory fields in json for create request. Check if fields exist during GET content request so that there is no panic.

**Comment by atonks2** [comment]
Thanks for the detailed issue @adotiyal. I just did some preliminary research and was able to reproduce the error. The codepath to create the file also validates the file's structure, but misses this case. We'll need to look further into the file validation and likely add additional logic around the cash letter control record.

**Comment by adamdecaf** [comment]
We can fix that panic. Thanks for the report.

A lot of these `*Control` records can be missing if they're fully computable. Since it's fields to compute we've allowed (in ach, etc) those fields to be missing and compute them prior to `.Write()` or `/contents` calls.
